### PR TITLE
get rid of llm usage

### PR DESCRIPTION
**Pull request by Necr0x0Der**

### CODE REVIEW

**Comment by besSveta** [comment]
https://github.com/zarqa-ai/metta-motto/blob/df328defc313759c95861cf4b9ca2e6212c8a4bf/examples/test_retrieval.metta#L9 is not working

**Comment by Necr0x0Der** [comment]
> https://github.com/zarqa-ai/metta-motto/blob/df328defc313759c95861cf4b9ca2e6212c8a4bf/examples/test_retrieval.metta#L9
> 
> is not working

What exactly is not working? `(Kwargs (doc_name "story1.txt"))` is not passed to the agent or what?

**Review by besSveta — APPROVED** [review]

**Comment by Necr0x0Der** [comment]
depends now on
https://github.com/trueagi-io/hyperon-experimental/tree/agents

**Comment by Necr0x0Der** [comment]
Can be merged after merging https://github.com/trueagi-io/hyperon-experimental/pull/778

**Pull request merged**
